name: Events Demo
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output Events Data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Test Code
        run: npm test
      - name: Build Project
        run: npm build
      - name: Deploy Project
        run: echo "Deploying..."
