name: Events Demo
on:
  pull_request: # specifying branches for pull requests is allowed to only trigger workflow
    types:
      - opened
    branches:
      - dev-*
  workflow_dispatch:
  push:
    branches: # you can specify branches the workflow will trigger after push
      - main
    # paths-ignore: # workflow will not trigger if none of the files in this folder changed
    #   - ".github/workflow/*"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output Events Data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Test Code
        run: npm test
      - name: Build Project
        run: npm run build
      - name: Deploy Project
        run: echo "Deploying..."
